apiVersion: v1
kind: Namespace
metadata:
  name: wyns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    owner/name: wy
  name: wy-tomcat-deployment
  namespace: wyns
spec:
  selector:
    matchLabels:
      app: wy-tomcat
  replicas: 1
  template:
    metadata:
      labels:
        app: wy-tomcat
    spec:
      containers:
      - name: myweb
        image: public.ecr.aws/docker/library/tomcat:jdk21-openjdk-slim-bookworm
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: wy-tomcat-svc
  namespace: wyns
spec:
   ports:
   - port: 8099
     targetPort: 8080
     nodePort: 30081
   selector:
     app: wy-tomcat
   type: NodePort
